### ISSUE TITLE
Define Joystick

### ISSUE THREAD

**Issue by Slade1972** [MiSTer-devel/C64_MiSTer#1]
This option, whilst appearing to work, in that you can define the Up, Down, Left, Right, Fire and Toggle keys, does not actually work inside the C64 / games. However the number pad on my keyboard works fine.

I've tested a number of different key combinations, none with success. Using the July release.

**Comment by sorgelig** [comment]
Did you define buttons in both Menu core and C64 core?

**Comment by Slade1972** [comment]
I wasn't aware it needed to be done in both cores, however I went back and tried that with no success.

I do have the WASD key combination working in the Genesis core, and that was prior to defining the buttons in the Menu core.

**Comment by sorgelig** [comment]
I don't know why it doesn't work. Not enough info. May be you misuse the feature somehow.
Will wait for other users with similar problem - then may be i can get some hint.

For me, all my game pads are working in C64 games.

**Comment by Slade1972** [comment]
You've misunderstood me. I don't have a USB OTG hub, so I'm only using a keyboard, and am trying to use the W,A,S,D, and I keys as Up, Down, Left, Right and Fire on a joystick - that is playing any C64 game using the keyboard as a joystick. Redefining the keys in the core works - the core shows the correct keycodes when I press the keys, but it doesn't work when I play a game.

What does work is the number pad with 2, 4, 6 and 8 working as Up, Down, Left, Right and 0 is fire. However I have not set these keys.

Setting the keys W,A,S,D in the Genesis / Megadrive core works fine - so this issue is localised to the C64 core.

**Comment by sorgelig** [comment]
i've just tested WASDI keys in joystick emulation and it works fine. I've played Turrican II on C64.
Are you sure you've switched your keyboard to joystick emulation?

**Comment by Slade1972** [comment]
I've tried again, on Turrican 1, this time. And still the same issue. I've tried setting the joystick emulation key to Home, 5 (on the number pad), End, P and various other keys with no effect.  Do I need to reset the C64 or Cold Boot the system for the changes to take effect ? Or are they immediate ?

Here is my C64 map file contents:
![image](https://user-images.githubusercontent.com/11675273/29749081-bc21820a-8b67-11e7-934d-601266ec2cc8.png)

And my FPGAGEN map file contents:
![image](https://user-images.githubusercontent.com/11675273/29749089-cfc2fe2e-8b67-11e7-8d81-e51a110321cc.png)

They're basically the same, where one works, and the other doesn't. Are you able to attach your C64 input map file for me to test ?


[C64_input_046d_c315.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/1254317/C64_input_046d_c315.zip)

**Comment by sorgelig** [comment]
I'm sure you didn't read wiki well. 
FPGAGen is keyboard-less console where keyboard is in joystick emulation permanently.
C64 is computer where keyboard works in keyboard mode originally. You need to switch to joystick emulation as per wiki description.

**Comment by Slade1972** [comment]
You're 100% correct. I was not paying full attention to the way the keyboard switched over. I was pressing the 'switch' key, not using the Num Lock / Scroll Lock keys to swap between the emulation modes.

Problem solved. Thanks.
