### ISSUE TITLE
Issues with games 

### ISSUE THREAD

**Issue by Marketing-Cerney** [MiSTer-devel/C64_MiSTer#101]
Arkanoid by Ocean just gives a black screen 

Hawkeye by Thalamus tape won't start the Mix-e-load II part of the loader, oddly Mix-e-load on Delta tape works

**Comment by sorgelig** [comment]
try this build:
[C64.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6911873/C64.zip)

**Comment by Marketing-Cerney** [comment]
yes that core fixes the Arkanoid issue 

The Hawkeye tape from CSDB works too, the odd thing is im sure the tape i had worked fine on a previous core revision. Its one of the few games that is actually nice to play from tape

**Comment by sorgelig** [comment]
Generally speaking if there is a tape version which works, then problem is solved. Some tapes can be a bad copy, for example it may have higher pitch or lower which may work in some conditions and don't work in others. 
Tell me which latest core version works with your older TAP, then i will see.

**Comment by Marketing-Cerney** [comment]
It's not a issue if there is a working Tap imho so I will close this
