### ISSUE TITLE
Issues with black screen or missing image in some demos 

### ISSUE THREAD

**Issue by Marketing-Cerney** [MiSTer-devel/C64_MiSTer#105]
Was going through some of the demo GFX froms this year and noticed that the following : 

Butt n cock ext (Transmission 2021) just gives a black screen

Colour_Barf (Borderline 2021) demo runs with music and border effects but black screen in the centre 

Happy 2021(Borderline 2021) Demo runs with music and border effects but blank screen in the centre 

New Members (Borderline 2021) Demo runs with music and border effects but blank screen in the centre 

Darklight by Loni (Gubbdata 2021) Black screen

**Comment by gyurco** [comment]
Do you know that the Borderline 2021 demos are about "only borders allowed"? The empty paper area is intentional.

**Comment by makigumo** [comment]
- Darklight by Loni (Gubbdata 2021) Black screen seems fixed, see also #110

**Comment by sorgelig** [comment]
everything from list is working already.
