### ISSUE TITLE
Screen Flickering in a new demo released from Lethargy

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/C64_MiSTer#108]
In the Lethargy group XXX demo, at 2.40 min , the screen makes an annoying flicker that doesn't appear on the original machine. I link to the demo as well as a video on YouTube, so that you can see the specific moment in which it blinks.
Demo file in: https://csdb.dk/release/download.php?id=255890
Youtube video:  (min 2.40) https://www.youtube.com/watch?v=kMBc7LXqNN0

**Comment by paich64** [comment]
Issue is still here, even on the MEGA65 c64 (ported from Mister). He is a video of the issue occuring (2:30) https://www.youtube.com/watch?v=LztIduc_0Mo

**Comment by paich64** [comment]
after further testing, this demo Needs CIA model 8521 to work properly. Runs OK on mister if in "Hardware" you switch to CIA model 8521.

**Comment by sy2002** [comment]
@lencio or @sorgelig Given @paich64 's discovery about the demo flawlessly running on CIA 8521 - is it fair to close this issue?
