### ISSUE TITLE
Request to implement a usb mouse as a 1351 Mouse

### ISSUE THREAD

**Issue by notcompute** [MiSTer-devel/C64_MiSTer#11]
for GEOS and some other programs a mouse would be nice.
so i kindly request the ability to use a usb mouse as a 1351 Mouse.

**Comment by notcompute** [comment]
if i have your attention anyway, just a quick question.
i mainly use the mister for its c64 core.
is there a way to transfer d64 files via usb flash drive?
i know it is not possible right now, but is it just because it is not implemented.
or is it because it is can't be done with a fpga.
if it can be done then i don't have to pursue this option any further.
Thank you for your precious time.

for quick checking out demo's it would be handy.

**Comment by sorgelig** [comment]
i don't understand what you mean by "transfer files". Do you want to copy d64 file from USB drive to SD card?

**Comment by notcompute** [comment]
if i have d64 files on the usb stick, i want to put the stick into the mister usb hub.
and then to mount the usb stick as a disk and load the d64 files.

that's the idea anyway

**Comment by sorgelig** [comment]
I really don't like the way when someone say "The X allows to do this" - I really don't care how it's done on other devices. It's more like "don't do it" for me. I'm not copying other emulators.
But MiSTer allows to use USB storage. 
Issue is not the place for help and guides. You can check the forum. Also Menu core has pretty much clear option to switch to USB storage.

**Comment by notcompute** [comment]
maybe it got lost in translation. i didn't ask for anything.
i just wanted to know if it was possible.

**Comment by notcompute** [comment]
> maybe it got lost in translation. i didn't ask for anything.
> i just wanted to know if it was possible to mount a usb stick as a disk and load the d64 files.
> 
> o yes did ask for usb mouse to use as a 1351 Mouse :-}

**Comment by sorgelig** [comment]
1351 Mouse will be added later

**Comment by notcompute** [comment]
thank you, i appreciate it
