### ISSUE TITLE
C64 Core. Multicolor + sprites picture not work

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/C64_MiSTer#110]
Hi, i run a .prg file from last Gubbdata 2021 party in c64 core and screen go black.
I tested it via HDMI and CRT(VGA/SCART).
The PRG in question is a multicolor + sprites picture (https://csdb.dk/release/?id=205510)
Tested in c64c, and Ultimate64 perfectly.

**Comment by makigumo** [comment]
Seems to work fine on latest release 20221007. So can probably be closed.
![20221030_184711-Darklight by Loni](https://user-images.githubusercontent.com/565430/198893343-8bab996c-22c7-4dfd-88c1-d51f9b9836cf.png)

**Comment by lencio** [comment]
Closed its works!
