### ISSUE TITLE
Kissmet[2021] Blank Screen after loaded.(c64 core)

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/C64_MiSTer#113]
Hi, i run a .prg file from last Revision Online 2021 in c64 core, and screen go black.
I tested it in  HDMI and CRT(VGA/SCART).
The program in question is https://csdb.dk/release/?id=202510

I run it in c64c, and Ultimate64 perfectly.

**Comment by rataweb** [comment]
Hi,
I tried and I got same issue. After the LOAD command, RUN command is autocompleted but, I got a black screen and nothing happens.

Thanks,
Shark

**Comment by tonypeters** [comment]
This is working now with latest core update

**Comment by lencio** [comment]
Closed!
