### ISSUE TITLE
Super Mario Bros. 64 v1.2 - misaligned sprites with core set to NTSC

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/C64_MiSTer#114]
[Homebrew port of Super Mario Bros. for Commodore 64, version 1.2](https://www.lemon64.com/forum/viewtopic.php?p=898195#898195)

This game has support for both PAL and NTSC machines, with a choice of 50 or 60 fps gameplay in game's main menu. The game operates properly with MiSTer core set to PAL, but setting the core to NTSC produces an issue regardless of 50/60fps ingame mode chosen. It seems like many graphics are misaligned to the left from their corresponding NES tile position. This is commonly exposed when hitting bricks.
![20211108_025817-Super_Mario_Bros_64_v1 2_-_Zeropaige](https://user-images.githubusercontent.com/70150033/140816822-5b7879fb-d35b-49ce-bc3f-7d8d264f6180.png)
![20211108_025832-Super_Mario_Bros_64_v1 2_-_Zeropaige](https://user-images.githubusercontent.com/70150033/140816837-65968972-41c6-4de3-93e6-577d5362dfe5.png)
(Block sprite appears to the right of expected position)
![20211108_181346-Super_Mario_Bros_64_v1 2_-_Zeropaige](https://user-images.githubusercontent.com/70150033/140816984-e69ba133-b1c2-411a-9e19-0796d5dbf169.png)
(Mario passes through the ? block when jumping into it from the left)
![20211108_181420-Super_Mario_Bros_64_v1 2_-_Zeropaige](https://user-images.githubusercontent.com/70150033/140817075-10e4ea0b-112e-4906-b749-004750838041.png)
(Mario being able to walk into objects)
![20211108_181508-Super_Mario_Bros_64_v1 2_-_Zeropaige](https://user-images.githubusercontent.com/70150033/140817169-67f5eac0-0187-4992-8cab-bdf224aa56ef.png)
![20211108_181541-Super_Mario_Bros_64_v1 2_-_Zeropaige](https://user-images.githubusercontent.com/70150033/140817178-8fdce5aa-2768-4446-8df2-c554157e0da4.png)
(Other misaligned sprites)

As said, this behavior happens only when MiSTer core is set to NTSC. This issue applies to both .d64 and .crt releases of SMB64 v1.2. This is unaffected by switching settings for REU, loadable KERNAL, second SID address (which this game supports) or C128 turbo mode (which this game supports).
The game behaves normally in VICE emulator.

**Comment by BluesM18A1** [comment]
I've seen this bug reported elsewhere about the Chameleon cartridge, seems to be a common issue with FPGA implementations of the NTSC VIC-II.
https://forum.icomp.de/index.php?thread/1693-bugs-ntsc-vic-ii-issue/&postID=15146#post15146

**Comment by gyurco** [comment]
I fixed this a while ago:
https://github.com/mist-devel/c64/commit/e832cd2347f1a3fc1c50491123fb3aa7deee7010

**Comment by Thelypody** [comment]
Game behaves as intended with the latest release. Thanks.
