### ISSUE TITLE
Final Catridge III - Issue with using mouse

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/C64_MiSTer#135]
How to reproduce:
- Load CRT of Final Catridge III
- Select Mouse on Hardware -> Pot1/2

What is the behavior:
we can click buttons of the mouse but the mouse doesn't move.

Thanks.

**Comment by sorgelig** [comment]
probably there are different versions of FC3 with mouse support and without..
i've tried FC3 Plus cart from this issue: https://github.com/mist-devel/c64/issues/5
It works. 
You need to select Mouse on Port 1 BEFORE load the cartridge (or do C64 reset after mouse selection).

**Comment by wwark** [comment]
Yes it works this way.
Thanks for your time !
