### ISSUE TITLE
Feature request: Physical User port

### ISSUE THREAD

**Issue by kiwanowski** [MiSTer-devel/C64_MiSTer#139]
https://www.c64-wiki.com/wiki/User_Port

An option to connect to:

C | PB0 | Data 0
D | PB1 | Data 1
E | PB2 | Data 2
F | PB3 | Data 3
H | PB4 | Data 4
J | PB5 | Data 5
K | PB6 | Data 6
L | PB7 | Data 7

There is an adapter that uses it: https://www.vandervecken.com/defmon/doku.php?id=docs:scannerboysync

**Comment by sorgelig** [comment]
there are no free I/O pins to implement it.

**Comment by kiwanowski** [comment]
What about a toggle for the USER_IO pins?

0 | D+ | RS232 RX
1 | D- | RS232 TX
2 | TX- | IEC /CLK
3 | GND_d | IEC /RESET
4 | RX+ | IEC /DATA
5 | RX- | IEC /ATN

**Comment by kiwanowski** [comment]
or just add PB2 and PB3 to USER_IO pins if there as some left

**Comment by sorgelig** [comment]
toggle to what? 6 pins are not enough for C64 user port.

**Comment by sorgelig** [comment]
not enough pins
