### ISSUE TITLE
All Hallows' Eve Demo by Atlantis & Bonzai & Genesis Project

### ISSUE THREAD

**Issue by francouai** [MiSTer-devel/C64_MiSTer#141]
Hello!

Just to let you know that the demo on the 2nd D64 disc is crashing. (ThePumpkins-Disk2.d64)
I'm getting a full freeze when using the last core "C64_20221007".
Can you have a quick check? Thanks!

https://www.pouet.net/prod.php?which=92727

**Comment by paich64** [comment]
I second this : 
- Tested ok on C64 true hardware
- Tested ok on Ultimate 64
- Fails on Mister C64 core
- Fails on Mega65 c64 core (ported from Mister core)

**Comment by francouai** [comment]
yup.. works perfect on real C64 hardware.

**Comment by sy2002** [comment]
Additional observation: While switching the CIA to 8521 (instead of using the default CIA 6526) fixes the bug in the XXX demo from Lethargy (as described here: https://github.com/MiSTer-devel/C64_MiSTer/issues/108), switching the CIA to 8521 does **not** fix the problem with All Hallows' Eve.

**Comment by francouai** [comment]
Fyi,
C64_20221110.rbf tested and still crashing.

**Comment by sy2002** [comment]
All, I've made an experimental build of the MEGA65 variant of the MiSTer core incorporating this fix from @gyurco:
https://github.com/mist-devel/T65/commit/7027ad169553911b1d55ce6d220364e7c8595b94

All Hallows' Eve works now like a charme from Disk 2 onwards.

Someone might want to to a test-merge on MiSTer, too.

**Comment by francouai** [comment]
I just tried C64_20221114.rbf and works great!
very impatient to use MEGA 65 core on Mister.

**Comment by sy2002** [comment]
@francouai Cool! I guess you can close the issue then :-)

**Comment by francouai** [comment]
until this core will be pushed out on the UDATE_ALL script from the Mister

**Comment by sorgelig** [comment]
@sy2002 
I don't know if you have relation to MEGA65 team, but I wonder if possible to get my pre-order of MEGA65 shipped finally? Ordered more than a year ago :(

**Comment by sy2002** [comment]
@sorgelig Yes, I do. I will send you a private answer in the private Patreon chat (I am a Patreon of yours and because this is the only way I can imagine at this moment how to send you you private message ;-) ).

**Comment by sy2002** [comment]
@sorgelig OK - please look at a message from "Mirko" in your private Patreon InBox.
