### ISSUE TITLE
Feature Request - External VPL palettes

### ISSUE THREAD

**Issue by Retro-Nerd** [MiSTer-devel/C64_MiSTer#144]
External palettes support would be nice. I really like the Colodore palette. Looks awesome using the Ultimate 64 FPGA Board. Any chance for an implementation? Presets with 50 and 75% saturation seems a good choice. The .vpl files can be found in the Vice emulator package, in the "C64" folder.  

https://www.colodore.com/

**Comment by sorgelig** [comment]
Generally speaking i'm against making Christmas Tree from a serious core such as C64. There are official C64 colors and they are pretty much defined.

**Comment by sorgelig** [comment]
Btw, if you use HDMI output, then there are new options in INI to control brightness/contrast. Additionally there is a gamma control option in OSD.

**Comment by Retro-Nerd** [comment]
Has nothing do to with a "Christmas Tree". Pepto made a mistake many years ago in measuring the C64 colors for emulators. They look wrong and way too desaturated. With the Colodore palette he corrected this and it looks much more like a real C64, connected to a TV/CRT monitor. I know it, because i still have several real C64 machines and CRT devices. 

It would be an optional feature anyway.

**Comment by sorgelig** [comment]
Well, i'm open to fix the palette if there is a error there.

**Comment by Retro-Nerd** [comment]
Well, maybe he couldn't do it better in 2001. I'm glad that he took the chance in 2016 to create a much more real life palette for the C64. I don't mind if you stay with his old settings, but an optional Colodore setting would be nice. Here is a little comparison.

Pepto PAL

![Pepto Colors PAL (measured 2001)](https://user-images.githubusercontent.com/38769713/215819726-b6aa8016-64f0-49dc-b9f4-37021dc2b8a1.png)


Colodore

![Colodore PAL (measured 2016)](https://user-images.githubusercontent.com/38769713/215820519-591030db-2220-4cb6-9271-9c0308f779f2.png)

**Comment by sorgelig** [comment]
That's something wrong with you TV or Monitor. On HDMI without any tweaks i see left picture with current palette.

**Comment by sorgelig** [comment]
I have no idea why you show screens from emulator as an evidence.

**Comment by Retro-Nerd** [comment]
Have you actually checked what colors you've implemented? On my LG C9 OLED Mister is closer to Pepto. It's not that purplish-blue like Pepto shown in the emulation screens, but  the C64 Mister Core looks definitely more like it than Colodore. There's nothing wrong with my TV.  Maybe  it's i'm be too picky though.  

"I have no idea why you show screens from emulator as an evidence."

Because taking photos from a Mister connected to a TV/Monitor doesn't make sense.  This would show wrong colors anyway.

**Comment by Retro-Nerd** [comment]
Ok, another try with real photos, because there are differences: 

Top = Ultimate Board with Colodore Palette loaded, no tweaks, SDR on my LG OLED 
Bottom = Mister C64 Core, no tweaks, SDR on my LG OLED (pretty much the same settings)

Example 1:

![Ultimate 64 Board with Colore Palette (SDR-No Tweaks- LG OLED)_1](https://user-images.githubusercontent.com/38769713/215899383-31e43462-2e1f-41d7-b237-be76dec24cd0.jpg)

![Mister C64 Core (SDR-No Tweaks-LG OLED)_1](https://user-images.githubusercontent.com/38769713/215902737-6cd27e29-8ab7-40bb-8d42-316e943b2687.jpg)


Example 2:


![Ultimate 64 Board with Colore Palette (SDR-No Tweaks- LG OLED)_2](https://user-images.githubusercontent.com/38769713/215903004-618a170c-99c9-4ca7-9acf-c02a47ce20a8.jpg)
![Mister C64 Core (SDR-No-Tweaks-LG OLED)_2](https://user-images.githubusercontent.com/38769713/215903022-4048650b-a4c6-4f1c-b4f2-d4e1abe2b53e.jpg)

**Comment by sorgelig** [comment]
> Ok, another try with real photos, because there are differences:

no difference basically. U64 version just uses "popped" colors. Upper can become bottom and opposite by simple brightness/contrast adjustment on TV. It's like Chinese/Korean phones by default use eye burning colors. So it pretends to be a "fresh" and "clear" colors while it's not.

Sorry, i don't buy it. There is no difference in general. I have real C64 too. I never saw reddish-brown on my C64.

**Comment by rsn8887** [comment]
If you look in the source code you would see we are already using the accurate colors from 2016 that you want, this has been the default in the core for years. See also here: https://github.com/MiSTer-devel/C64_MiSTer/pull/56

**Comment by Retro-Nerd** [comment]
I guess you've implemented the conservative 50% saturation from the Colordore image settings generator. Anyway. I did some tinkering with the Mister.ini saturation and contrast boost (video processing settings), together with the LG OLED "white balance" setting of "warm3". This mimics my Sony Trinitron TV pretty close. Case closed (from my side, as it was closed anyway before.

**Comment by BluesM18A1** [comment]
How hard can it be to just let people load in their own palette file like you can with the NES core? People are going to be arguing about what the """correct""" colors are for the VIC-II until the end of time just like with the NES PPU, and since different board/chip revisions combined with different monitors are always going to produce different results, you may as well let people customize it on their own.
