### ISSUE TITLE
Issue: Color palette

### ISSUE THREAD

**Issue by Maverick-Shark** [MiSTer-devel/C64_MiSTer#150]
Hi,

C64 core has an incorrect color palette. MiST is better and it looks like the original c64.

Left: MiSTer
Right: MiST

![image](https://user-images.githubusercontent.com/10196716/234349749-9bae97ac-3e96-47f9-b828-c8014b10c04a.png)

Regards,
Shark

**Comment by rsn8887** [comment]
No. The colors on Mist are wrong, old Pepto. Real C64 never looked that way. Even Pepto himself has since redacted those colors.

See here: https://github.com/MiSTer-devel/C64_MiSTer/pull/56

and here: https://github.com/MiSTer-devel/C64_MiSTer/issues/144#issuecomment-1412727753

**Comment by Maverick-Shark** [comment]
> No. The colors in your Mist example are the wrong, old Pepto palette. A real C64 never looked that way. Even Pepto himself has since redacted those colors. MiSTer is more accurate.
> 
> One should not compare to other simulator or emulator, only compare to real C64 (using SVideo).
> 
> See here: #56
> 
> and here: [#144 (comment)](https://github.com/MiSTer-devel/C64_MiSTer/issues/144#issuecomment-1412727753)

Could you add an option (OSD Menu) to select different palettes? Like c64, Pepto, Colodore...

Thanks,
Shark

**Comment by sorgelig** [comment]
C64 didn't have programmable palettes. I don't see a reason to invent this.

**Comment by sorgelig** [comment]
I have real C64. And it no way near to the right pic. It's very close to left pic.
