### ISSUE TITLE
C64 (some) demos do not detect disk change

### ISSUE THREAD

**Issue by bbirkinbine** [MiSTer-devel/C64_MiSTer#153]
In running demos on the C64, I notice that some demos do not detect the disk change and therefore cannot continue with the demo.

2 demos where new disk isn't detected
- h2k by plush
- soiled legacy by resource

An example demo that detects disk change correctly and proceeds
- edge of disgrace by booze

**Comment by bbirkinbine** [comment]
this appears to be fixed.  both h2k and soiled legacy demos worked correctly on disk change.  not sure which update fixed this issue, but closing.

**Comment by paich64** [comment]
> this appears to be fixed. both h2k and soiled legacy demos worked correctly on disk change. not sure which update fixed this issue, but closing.

On which exact core version did you test ?

**Comment by bbirkinbine** [comment]
Based on my NAS history of the C64 core on my Mister.

-rwxr--r-- 1 nas nas 3743120 Aug  2 13:04 C64_20230517.rbf*
-rwxr--r-- 1 nas nas 3724640 Dec 16 18:16 C64_20231208.rbf*

Likely saw the issue on C64_20230517 and noticed it working on C64_20231208 after an update_all

**Comment by paich64** [comment]
Many thanks, much appreciated. Actually it really looks like to be random.
