### ISSUE TITLE
speeddos 2.7 does not work properly - load speed to slow

### ISSUE THREAD

**Issue by Videodr0me** [MiSTer-devel/C64_MiSTer#154]
The provided speeddos 2.7 roms do not seem to work properly. Load speeds are much to slow - on par with a stock 1541. Either the parallel connection is not properly configured in Mister or the drive rom is not correct. The speeddos kernal rom falls back to normal stock 1541 speed and provides no speedup whatsoever. It would be nice to get speeddos working. Dolphin dos works and is faster but has many more software incompatibilites.

**Comment by sorgelig** [comment]
Should be fixed in new release. Make sure you've updated the rom file - it should be bigger by 16kb.

**Comment by Videodr0me** [comment]
Yes! It works now! Thank you very much! From all the important fast loaders now only professional dos (the absolute fastest, faster than dolphin and also more compatible) and pro-logic dos (speed like dolphin dos, only more compatible) are missing..... hardware wise pro-logic should be extremely similar to dolphin and professional dos is also similar but adds some minimal extra adress decoding logic to access the gcr tables faster....

**Comment by sorgelig** [comment]
After reading professional dos HW differences it makes me doubt about better compatibility as they change in addressing a lot. Custom loaders in 1541 won't like such changes.

**Comment by Videodr0me** [comment]
In practice professional dos it is more compatible. This has less to do with the disk drive side of things but more with the kernal changes on the c64 side. Unfortunately dolphin-dos breaks more software than the other fastloaders - there are lists over on forum64. Professional dos would be nice but if its to much work, i can live with falling back to speed dos for those titles. 

I recently checked the professional dos v3/4 support by the c64 emulator denise and it works finem maybe the source code of denise provides more insight into implementing the addess logic...
