### ISSUE TITLE
REU and GeoRAM do not function in recent builds

### ISSUE THREAD

**Issue by rhester72** [MiSTer-devel/C64_MiSTer#155]
I don't know when the problem started, but as of at least build 20230517, no software I've tested (1764 Test/Demo RAMTEST or demos, GEOS 1.3/2.0) detects the REU at all (in 512MB or 2MB mode, 16MB mode untested)

Default configuration is enough, just turn the REU on and test.

If helpful at all, this problem does NOT occur in the most recent C128 core build, dated 20230325.

Further testing has shown that GeoRAM does not work either (but does on the C128 core).

**Comment by sorgelig** [comment]
I've just tested REU with 17xx-REU-mem-tester.d64 and GeoRAM with GeoRAMChecker.d64
Both are working fine. Try to reset settings of core to default. Some hardware settings may interfere each other.

**Comment by rhester72** [comment]
Completely user error.  :/

I have an Epyx Fastload cartridge loaded by default.  The REU also goes into the cartridge slot.  *headslap*
