### ISSUE TITLE
Digitized samples are too soft on 6581 setting.

### ISSUE THREAD

**Issue by rikard-softgear** [MiSTer-devel/C64_MiSTer#16]
On a real C64, samples are usually loud and clear played back on a 6581 SID, and really quiet on an 8580. The MiSTer seems to do the opposite: Loud 8580 and quiet 6581. (Not nearly as soft as the real 8580, though. I'm not sure that's desireable.)

Recordings of the real deal:
http://anorien.csc.warwick.ac.uk/mirrors/oakvalley/soasc/hvsc/049/MUSICIANS/T/Tel_Jeroen/Turbo_Outrun_T01.sid_MOS6581R2.mp3

http://anorien.csc.warwick.ac.uk/mirrors/oakvalley/soasc/hvsc/049/MUSICIANS/T/Tel_Jeroen/Turbo_Outrun_T01.sid_CSG8580R5.mp3

PRG file to play back the music on MiSTer:
[Turbo_Outrun_SID.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/3563844/Turbo_Outrun_SID.zip)

This happens with other digi-tunes too.

(I have no way of making recordings of the MiSTer, otherwise I would add them here.)

**Comment by sorgelig** [comment]
This is not what can be simply fixed. If you are good in modeling analog filters in numbers, then you are welcome to improve it. Otherwise it will stay as it is.
Jotego has plans to make a new SID module. How it will be precise to emulate the filters - time will show.

**Comment by rikard-softgear** [comment]
Sorry, I did not understand that this was dependent of any analog modelling.

**Comment by sorgelig** [comment]
yes, samples are playing without filters. Filters add the "color" to the samples - whet you call soft/sharp/etc.

**Comment by sorgelig** [comment]
not sure if it's still relevant issue after mane changes in SID.

**Comment by sorgelig** [comment]
it should be fixed several releases ago
