### ISSUE TITLE
SuperSnapshot cartridge handling

### ISSUE THREAD

**Issue by darylrichards** [MiSTer-devel/C64_MiSTer#161]
The original Super Snapshot v5 cartridge can actually handle a larger image (128k vs 64k) and that is used by the SnappyROM upgrade.

This change adds support for the extra address line and doesn't affect using the old 64k ROM either.

[ssv5.patch](https://github.com/MiSTer-devel/C64_MiSTer/files/13801704/ssv5.patch)

**Comment by sorgelig** [comment]
So, did you verify 64K version and they don't place garbage in higher bits?

**Comment by darylrichards** [comment]
I loaded up all the .crt images I could find, and with a quick test each one worked. Considering the original cartridge always had A16 wired to a 32 pin socket, I can only assume the author considered it and wrote the code accordingly.

[https://rr.c64.org/wiki/File:Super_Snapshot_v5_Schematics.gif](url)

Is there a way in the framework to know how many bytes were loaded from the file? That would allow for a quick masking of the higher address line.

**Comment by sorgelig** [comment]
Yes. So i will need to take care about this.

**Comment by paich64** [comment]
> The original Super Snapshot v5 cartridge can actually handle a larger image (128k vs 64k) and that is used by the SnappyROM upgrade.
> 
> This change adds support for the extra address line and doesn't affect using the old 64k ROM either.
> 
> [ssv5.patch](https://github.com/MiSTer-devel/C64_MiSTer/files/13801704/ssv5.patch)

If it's all about being to use this CRT/ROM on the mister [](https://github.com/adrianglz64/snappyrom) then it's a super nice addtion since it provides the best possible retro coding environment :)

**Comment by sorgelig** [comment]
I've pushed changes, please test it.

**Comment by darylrichards** [comment]
Works like a charm for me! Thanks!
