### ISSUE TITLE
Feature Request: On screen LED's

### ISSUE THREAD

**Issue by Jammmmm** [MiSTer-devel/C64_MiSTer#168]
Any chance of seeing on screen LED's so I know when a drive or tape is being accessed?

I know it makes it feel more like emulation rather than an actual system, but it's a feature that I've found extremely useful in emulators.

Example in Vice showing drive 8 being accessed:
![led](https://github.com/MiSTer-devel/C64_MiSTer/assets/19413305/8ef6b981-ad1f-4c9c-bdc9-4825f0d8983d)

**Comment by sorgelig** [comment]
As you already mentioned - it's emulator specific options. MiSTer uses I/O board LED to show disk activity.

**Comment by Jammmmm** [comment]
My MiSTer sits at my TV while I'm sitting on a couch far away so I never see the LED's :P 

But that's ok. Thanks, @sorgelig !
