### ISSUE TITLE
No support for .T64 extension

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/C64_MiSTer#17]
Not really a big issue. I am pretty sure .T64 files are the same as .TAP. Maybe the .T64 extension could also be supported? This would be useful for Gamebase64 files.

**Comment by sorgelig** [comment]
T64 and TAP are different formats.
Anyone can add T64 format. I have no plans for this. 
With Disk read/write support, tape is pure optional feature where simple TAP format is pretty much enough.

**Comment by rsn8887** [comment]
Fixed in release 20200122! I love it :)
