### ISSUE TITLE
Option to map up twice

### ISSUE THREAD

**Issue by KridTheInsane** [MiSTer-devel/C64_MiSTer#173]
For some platform games it would be nice to jump with a controller button, but for example Jack the Nipper 2 you also need to go up and down on a rope then you also need the up on the controller to do that.

I'm a big C64 fan. And i know the original way to play was just joystick up to jump. But it makes games so much more enjoyable now to press a button for that.

**Comment by rsn8887** [comment]
This can already be done via the "Button/Key Remap for Game" option in the core options. 

Instructions:
- Map your controller normally
- Select "Button/Key Remap for Game" in Core Options
- Press the alternative button you want to use for jump
- Press up on your dpad or joystick

Now both the alternative button and the up direction will cause jumping in the game. Tested with Giana Sisters.
 
See also my video at timestamp 8:04 here (shown for Amiga but works on C64 as well):
https://youtu.be/8tGPDTcuDSE?si=sTTw4Jhwt5l6dw_K&t=484

**Comment by KridTheInsane** [comment]
Thanks for this, it works perfect now!
