### ISSUE TITLE
tape loading is not working

### ISSUE THREAD

**Issue by goofyseeker311** [MiSTer-devel/C64_MiSTer#174]
this should auto-play when tape is mounted,
but even <load "*",8,1> says "device not present" when a tape is loaded.

**Comment by sorgelig** [comment]
"8,1" means load from disk.
load from tape is `load "*"`
But make sure you use original (not modded) kernal. Modded kernals usually have tape routines removed.

**Comment by goofyseeker311** [comment]
I use default c64 without any extras.
if the normal kernal is not the default option then it should be in the core default setting.

**Comment by sorgelig** [comment]
> the 8 means try disk first, 1 means try tape next

No. It means load from device 8 (disk), using address supplied in header (1).
Please read C64 kernal docs and get familiar with it.

**Comment by goofyseeker311** [comment]
thanks, device 1, tape, I tried that with <load "*",1> which does not work either.
<load "*",8,1> is the default loading command for all things, like internet says.

**Comment by sorgelig** [comment]
If you don't want to listen what i've said, then as you wish...
Tape works when it's done correctly.

**Comment by goofyseeker311** [comment]
just say if the c64 core requires an external loaded rom to get it working.

**Comment by sorgelig** [comment]
just load the tap file and in basic enter:
`load "*"`

**Comment by sorgelig** [comment]
actually simply `load` is enough

**Comment by goofyseeker311** [comment]
about those arcade cores with joystick.
keyboard bound controls do not work with some cores.
then I tried joystick, which is not reliably working.
I explained the joystick control saving issue the the distribution issues.

**Comment by goofyseeker311** [comment]
I have already run some of the .tap files on c64forever UAE emulator, so its not a game file issue.

**Comment by goofyseeker311** [comment]
I suspect that the normal dolphin dos in the c64 core does not have routines for tape by default.

**Comment by goofyseeker311** [comment]
solved. it was dolphindos loading automatically and being doubly annoying to remove from loading by default.
I suspect this came from the distribution mister package installing them automatically.
