### ISSUE TITLE
"It's Magic" graphic glitch

### ISSUE THREAD

**Issue by Jammmmm** [MiSTer-devel/C64_MiSTer#175]
![itsmagic](https://github.com/MiSTer-devel/C64_MiSTer/assets/19413305/986c1ae3-716e-4a93-95e4-2db20fd1cb00)

As seen in the attached GIF, the diamond is buggy. On a real C64 (and on WinVICE), it displays correctly.

Using a regular PAL C64 setup in MiSTer and the image from Gamebase64 ([Success (SCS) & The Ruling Company (TRC)](https://gb64.com/game.php?id=3854&d=18&h=0))

**Comment by mambrino** [comment]
I've tested with the same gamebase image (SCS) and it works perfectly in my config, diamonds are drawn without glitches, do you have the latest version of core and firmware? maybe something different in the core config?

**Comment by Jammmmm** [comment]
Thank you so much, @mambrino, for letting me know it works. That led me to tweak some settings and find that Dolphin DOS (ie. "Loadable C64" in MiSTer) was the issue. Switching to "Standard C64" fixes the glitch, so that's been solved! :) Have switched to Action Replay 6 Pro as my fast loader and that works just fine.

I've been using Dolphin DOS for years and this is the first glitch I've personally seen, so it's good to know.
