### ISSUE TITLE
Which license is applicable ?

### ISSUE THREAD

**Issue by vpelletier** [MiSTer-devel/C64_MiSTer#18]
I recently bought the hardware and successfully soldered an SDRAM daughterboard. I'm impressed by the emulation quality and the number of supported systems.

I have been wanting to write in HDL for a while now, and I see the presence of C64 combined with the lack of C128 as a perfect learning opportunity. I started hacking together the 1571 HDL, starting from the 1541 implementation present here.

But then I stumbled on the VIA implementation, which header mention terms of use which are incompatible with the GPL v2 (at least):
```
--              Please note: A LOT OF REVERSE ENGINEERING has been done to
--              make this module as accurate as it is now. Please do not copy
--              (use in your own projects) without written permission of the
--              author.
```

The 1571 has a pair of VIA chips, like the 1541, so I would very much prefer to be able to reuse some existing code - but I am not comfortable with such licencing terms.

Could you clarify how is this licence affects C64 development, derivative works, and their distribution ?

**Comment by sorgelig** [comment]
This is stupid clause written by original author of this module. If you care so much then there is a e-mail, so you can contact the author.
My principle is simple - if source code is released then it's free to use in other open source non-commercial project.
There are other HDL implementations of VIA 6522. Check VIC20 repository for example.
