### ISSUE TITLE
Emulamer Errata demo does not work

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/C64_MiSTer#22]
Hi, Emulamer’s demos do not work.
First of all the three step of emulamer’s Errata demo do not work.

Demo:
https://csdb.dk/release/?id=104805

Emulamer’ demos work on ViceSC, Hoxs64 and are all supported in The great MacOs emulator VirtualC64.

**Comment by DaitarnIII** [comment]
Yes, this demo does not work, not good for an hardware re-implementation !
**6569** and **glue logic custom** must be implementate for this demo.

**Comment by sorgelig** [comment]
Then fix it! What's you waiting for?

**Comment by gyurco** [comment]
Is there any video how this demo should look like? It doesn't seem correct even in VICE. No upper scrolling text on page 2 for example.

**Comment by Alessandro1970** [comment]
Errata demo in ViceSC works well, use 6569 and glue logic custom.
If you have a mac it works great on VirtuaC64.
https://csdb.dk/release/?id=104805

**Comment by Alessandro1970** [comment]
Now it goes better but the upper written are wrong and the third step demo are not painted correctly by Vic timing:

on VirtualC64:
<img width="723" alt="Schermata 2020-04-05 alle 09 38 13" src="https://user-images.githubusercontent.com/34916641/78469411-41d00780-7721-11ea-8ccb-113f8afe8788.png">


Note in the sep two in the upper screen must compare the written "Congratulation", one letter at time...

**Comment by gyurco** [comment]
Finally found the solution for part3  (and Ruined Art, too).
Now only part2 is broken - any idea what trick is used there?

**Comment by gyurco** [comment]
Found it: several undocumented opcodes have different behavior if the CPU is not RDY. Need to hack on the T65.

**Comment by Alessandro1970** [comment]
...for undead demo should be to implement glue logic custom id

**Comment by gyurco** [comment]
That's one quirk of the PLA in C64C. That demo won't work with the old PLA in the breadbin.

**Comment by gyurco** [comment]
I wonder what's so special in the 6569 VIC-II to display that secret message.

**Comment by Alessandro1970** [comment]
...it’s a kind of magic. ;-)

**Comment by gyurco** [comment]
I found something which might work. But:
6569 is the old PAL VIC-II.
The custom logic PLA is in the newer C64Cs, where the VIC-II presumably is a 8xxx.
Thus no real machine could display all of the Emulamer demos.

**Comment by Alessandro1970** [comment]
Maybe in rhe C64 config the user could chose from old cia to the new, and so on with the cpu and glue logic ...like in the ViceSC emulator.
Btw emulamers works well in hoxs, vice and virtualc64 emulators

**Comment by Alessandro1970** [comment]
Have you used Vice whit old c64 default settings or c64c settings ?
It works in the same mode in displaying flashing letters in the upper part in the step n.2 over the big written.

**Comment by gyurco** [comment]
The trick used for that text is documented in the VIC-II addendum:
https://sourceforge.net/p/vice-emu/code/HEAD/tree/techdocs/VICII/VIC-Addendum.txt
Section [Fetch]
It's stupid enough that I won't play with that, but if anyone can implement it, then that would be good.

**Comment by Alessandro1970** [comment]
@gyurco 
Thank you for your great job. 
One thing to say

For the written in upoer screen in part 2 of Errata:

1) if you have a 8565 cpu you do not see anithiyng (none)

2) if you have a 6569 (C64 breadbin) you must see the letters in upper screen

...so if the core implements a 8565 none letters in upper screen have to be seen to close issue

**Comment by Alessandro1970** [comment]
C64c 8566 none is shown:
![694AF215-83A7-46FD-A66E-E67452686FF7](https://user-images.githubusercontent.com/34916641/80800038-b70bec80-8ba8-11ea-8d10-48b77b33033c.jpeg)

C64 breadbin secret message:
![2C8A6BD2-612E-48D4-8681-E35CB5B40DA4](https://user-images.githubusercontent.com/34916641/80800046-c4c17200-8ba8-11ea-8637-65b4649fea9b.jpeg)

**Comment by Alessandro1970** [comment]
...but if the VicII model implemented in Mister is the 8565 then no letters have to be seen in the **upper screen** of the **second part** in this demo.
The same thing in Conclusion demo: after the written "use 6569" no letter have to be seen (if 6569 was selected a "Congratulation" flashing letters have to be seen one atfter one.

**Comment by rossimariolee** [comment]
Hi,
The flashing letters, in this demo (part two - upper screen) using the Vic 8565 (C64C) have not to be seen.
It is a bug, no flashing letter in that area, they have to be seen only if the VIC is the one used in the breadbin (6569).
For other things the implementation is wonderful. 
**_Please remove this bug_** Do not forgive C64-FPGA users... Bye

**Comment by sorgelig** [comment]
Already explained above.
Games aren't using this.
