### ISSUE TITLE
Keyboard buffer missing?

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/C64_MiSTer#23]
While loading from a floppy disk on a C64 you can type e.g. RUN and the command will appear along with the cursor when the floppy drive is done loading. Now you can simply tap Return to run the loaded program.

Isn't that supposed to work on this core too? (it doesn't)

**Comment by sorgelig** [comment]
i think it's possible only on emulator. Real C64 has no keyboard buffer AFAIK.

**Comment by dfilskov** [comment]
My mistake - it **does** work on MiSTer when switching to standard kernal (but not when using the loadbable "mister"-kernal) - so nothing wrong with the core nor the kernals - the kernal I used simply doesn't register while turbo loading :)
