### ISSUE TITLE
additional option to load D64 or PRG with just one menu-function

### ISSUE THREAD

**Issue by fanattic** [MiSTer-devel/C64_MiSTer#25]
A great improvement would be to be able to access D64 and PRG with the same menu-function (additionally). So we won't have to split the collection into different sections for each filetype!

**Comment by sorgelig** [comment]
You don't have to split your collection. You can keep both types in the same folder.
D64 is mounted while PRG is loaded - they cannot be combined.

**Comment by fanattic** [comment]
sure, but if i enter f.e. a sub/sub/sub/subfolder to browse and find something i want to try i don't know what kind of filetype it is. if its a D64 and i have chosen PRG in the main menu i have to go back, chose D64 and enter the sub/sub/subfolder again. would be much easier with a universal load option in the menu which recognizes the filetype by ending and uses the fitting loading routine automatically.

**Comment by sorgelig** [comment]
This is because you don't follow standard of folders.
In SD card create C64 folder in the root (/media/fat/C64 or /media/fat/games/C64) and put all C64 files there. You can put D64 and PRG into the same folder. You will see only D64 or only PRG depending on option.
