### ISSUE TITLE
Bugs observed from a day watching demos

### ISSUE THREAD

**Issue by sajattack** [MiSTer-devel/C64_MiSTer#29]
Part way through, [comaland](https://csdb.dk/release/?id=139278) fades to black and never comes back, if you look it up on youtube it's supposed to fade to black then fade back in. 
https://youtu.be/470On9iqPXc?t=205

[Deus Ex Machina](https://csdb.dk/release/?id=11585) had this garbage on the screen 
![20200108_055118-screen](https://user-images.githubusercontent.com/1562711/71954012-c0f08680-3198-11ea-9d1d-c0b08d71bca0.png)

There were a couple others I didn't capture or fully remember well enough to document. I'll keep you posted.

**Comment by sajattack** [comment]
[The dive](https://csdb.dk/release/?id=179128) crashed completely.

**Comment by sajattack** [comment]
[Concert](https://csdb.dk/release/?id=151274) had similar screen garbage to Deus Ex Machina 
![20200108_230210-screen](https://user-images.githubusercontent.com/1562711/72023617-217ad480-3228-11ea-8245-b90a466040f5.png)

**Comment by M-Walrus** [comment]
I'd like to add Memento Mori to the list of demos with graphical corruption.  Everything is fun up until Disk 3, where you can see flickering graphical corruption in a column towards the right side of the screen.  The corruptions continues throughout this long scrolling section:

![Memento Mori Disk3 Graphics Gltich](https://user-images.githubusercontent.com/40709481/110237080-69b28700-7eff-11eb-8f7a-0a50a18b4872.png)

**Comment by raparici** [comment]
Update on demo compatibility. As of May 9th 2021:

No crash in The Dive
No graphic corruption on Deus ex Machina
No graphic corruption on Concert
No black fade in Comaland

Current known issues: vertical glitch in the right border in Memento Mori as reported by M-Walrus + in Comaland disk3 other vertical glitch in the right border.

**Comment by sorgelig** [comment]
comaland and memento mori are fixed now too.
