### ISSUE TITLE
Ability to load custom kernel rom and 1541 rom from SD

### ISSUE THREAD

**Issue by Quantum-cross** [MiSTer-devel/C64_MiSTer#3]
Would it be possible to add an option to load a custom kernel rom and 1541 rom from sd card? This would enable usage with the JiffyDOS fast loader.

**Comment by sorgelig** [comment]
it's already supported.
combine C64.rom+C1541.rom => boot.rom and place it into C64 folder.

**Comment by Quantum-cross** [comment]
Nice to know the feature is in! But I am still having trouble with this, no matter what roms I use I get a black screen on the start of C64 core.

**Comment by Quantum-cross** [comment]
Got it, have to stuff (8KB Basic rom) + (8KB Kernel rom) + (16KB 1541-II rom)!
