### ISSUE TITLE
OPL2 FM volume mixing seems incorrect

### ISSUE THREAD

**Issue by shazz** [MiSTer-devel/C64_MiSTer#30]
Hi,

I tested multiple FM demos for the C64 (on my C64 with an FM card, some captures on youtube and on the C64 core) and the result is fairly different on the C64 core. Maybe how SID and OPL2 outputs are mixed ?

Example:
Midnight Kisses - Mibri
 - YT: https://www.youtube.com/watch?v=xP1JnE5aGb0&list=PLP26ZYnLb5EX_XZMC16RuaOAKjaxEzsx
 - PRG: https://csdb.dk/release/?id=185704

Same weird behavior with other FM releases.

**Comment by sorgelig** [comment]
i think it's more or less ok now
