### ISSUE TITLE
[Feature request] Create blank floppy files

### ISSUE THREAD

**Issue by Kashouryo** [MiSTer-devel/C64_MiSTer#38]
I am working with a software that saves and loads documents from a floppy disk. Is it possible to create a blank floppy file and mount it with the core it self?

Thank you

**Comment by Hackshed** [comment]
I just copied a .dsk file and renamed it "blank" 
Insert into the C64 and format it the usual way. You can copy it as many times as you like from the file manager

**Comment by sorgelig** [comment]
i think it's not an issue. Just mount an image.
