### ISSUE TITLE
OMIUC demo, flicker and graphic errors when big rotating Pyramid appears

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/C64_MiSTer#45]
Hi,
OMIUC demo has some problems (graphic errors) when big rotating Pyramid appears.

You can see it here:
https://archive.org/details/c64_OMIUC-side1

**Comment by sorgelig** [comment]
i don't see any issues in the whole demo.

**Comment by Alessandro1970** [comment]
I have updated Mister and the demo works well.
It remains to resolve Emulamer’s Demo (Errata (mostly on third part, Ruined art, Undead [Glue logic -custom ic]...

Great job, thank you!
