### ISSUE TITLE
Reset acts like a power cycle and clears memory

### ISSUE THREAD

**Issue by TalRepair** [MiSTer-devel/C64_MiSTer#47]
RESET will clear memory. That makes it impossible to program assembly. OR modify the memory in a monitor. Can you make it not wipe the memory and act like a soft reset so all assembly will stay in tact. This is how the real c64 works too. Also add to map a button for RESET.

**Comment by sorgelig** [comment]
BIOS of C64 unfortunately uses uninitialized memory, so it simply impossible to restart C64 after some games/apps without clearing the memory.

**Comment by jstavats** [comment]
The soft reset functionality sought is similar to that demonstrated in the following video at 7:45, where the reasoning is given.

https://youtu.be/V5bx16b2420

I’m not sure why the BIOS makes that impossible to implement.

**Comment by Hackshed** [comment]
The video shows a modern re-implementation of the C64 Maxi and not the original C64 (which is what the core is based on).
Sorgelig is correct in that the C64 had no built in way of performing a soft reset and this feature was added to dedicated cartridges for the C64.

In its day, one of the most useful "freezer" cartridges was the Action Replay cartridge.
I use this with my core and have it set to insert at boot (rename the file to boot3.rom)
F11 will bring up the AR freeze menu which also includes a built in machine code monitor to assist with assembly programming

Hope this helps

**Comment by sorgelig** [comment]
implemented as an option.
