### ISSUE TITLE
Ram Expansion?

### ISSUE THREAD

**Issue by zBeeble42** [MiSTer-devel/C64_MiSTer#48]
So... playing with the software C=64's, RAM expansion cartridges make many things (like turbo macro pro) _MUCH_ better.  Anyone working on REU carts?

**Comment by M-Walrus** [comment]
I would also like to see the ram expansion hardware be integrated into the core.  Games like Sam's Journey can only play NTSC with that in place.

**Comment by Andypapa99** [comment]
We would as well love to have the opportunity to use GEOS or advanced games that need the Commodore RAM extension unit (REU) ... is there any chance to see that in the near future ?

**Comment by M-Walrus** [comment]
The ram expansion has been added and I tested it with a variety of applications like Sams Journey NTSC, Breadbox music demo and FMV. 

This request/issue can be closed.
