### ISSUE TITLE
Request: Ability to temporarily bypass custom kernal boot.rom file, or select from list.

### ISSUE THREAD

**Issue by verm71** [MiSTer-devel/C64_MiSTer#5]
If one has a custom kernal consisting of, example, JiffyDOS in boot.rom, it is not straightforward to bypass that custom kernal temporarily for one session, say for loading a game which is not compatible with JiffyDOS. The only way I know is to rename boot.rom until needed again, but this is not feasible from the menu interface.

**Comment by verm71** [comment]
The boot.rom injector solves this issue.

**Comment by sorgelig** [comment]
implemented

**Comment by verm71** [comment]
And very handy. Thanks!
