### ISSUE TITLE
Demo not run

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/C64_MiSTer#51]
Hi to all!
I'm new in mister, and I'm wonder with this FPGA.

I found many demos that not work in c64 core.
For example: https://csdb.dk/release/?id=163621
The screen go black and do nothing.
This demo is tested on all my real c64 and runs fine.
Any ideas?

P.D. I have mister and cores updated.

**Comment by sorgelig** [comment]
version vfssdpcm1superplus-loaderupdate.d64 works
It's about non-standard C1541 use in some demos/games which may fail with some very tricky loaders.

**Comment by lencio** [comment]
Thanks for reply! i'l go to close ticket.
