### ISSUE TITLE
Feature request: Reset C64 core when loading a new PRG

### ISSUE THREAD

**Issue by limi** [MiSTer-devel/C64_MiSTer#52]
With the great work done in the [OneLoad64](https://misterfpga.org/viewtopic.php?f=12&t=1540) collection, many of the most popular C64 games are now available as instant-load PRG files.

However, if you have loaded a game in this fashion, and then try to load a different one, it will not work, since you need to reset the C64 first.

It would be great to make it the default behavior that loading a new PRG resets the C64 core first, same as is the case with Cartridges. [See how VICE does it as an example](https://www.youtube.com/watch?v=9xZssapU9yY&feature=emb_title).

(If there’s a use case for loading a PRG and *not* resetting first, this could be an option, but the majority case is likely to be loading a new game for most people)

**Comment by lencio** [comment]
> With the great work done in the [OneLoad64](https://misterfpga.org/viewtopic.php?f=12&t=1540) collection, many of the most popular C64 games are now available as instant-load PRG files.
> 
> However, if you have loaded a game in this fashion, and then try to load a different one, it will not work, since you need to reset the C64 first.
> 
> It would be great to make it the default behavior that loading a new PRG resets the C64 core first, same as is the case with Cartridges. [See how VICE does it as an example](https://www.youtube.com/watch?v=9xZssapU9yY&feature=emb_title).
> 
> (If there’s a use case for loading a PRG and _not_ resetting first, this could be an option, but the majority case is likely to be loading a new game for most people)

With this "feature" we can't use any freezer like action replay, FC3, etc when I run any PRG. Result c64 core is useless for debuging, infinite lives, etc...
its possible to revert this feature please?

**Comment by sorgelig** [comment]
implemented
