### ISSUE TITLE
Feature Request: More Accurate Palette / Custom Palettes

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/C64_MiSTer#55]
The C64 only had 16 fixed colors. There's no true perfect C64 palette, only various approximations. Therefore, I think it would be cool if the core supported loading custom palettes.

One palette I would like to be able to load would be the so-called "Colodore" palette, which is the corrected and improved version of the old "Pepto-Pal" palette, created by the same person. There is an example here:
https://www.colodore.com/

**Comment by rsn8887** [comment]
The Gameboy core already supports loading custom palettes, maybe some code could be re-used?

**Comment by rsn8887** [comment]
Here's another link explaining the colodore palette:
https://www.pepto.de/projects/colorvic/

**Comment by rsn8887** [comment]
It looks like the core currently uses the old PEPTO-PAL palette from here:
https://www.pepto.de/projects/colorvic/2001/

But PEPTO-PAL has been superseded. The same author has since improved his calculations and created the improved COLODORE palette, here:
https://www.pepto.de/projects/colorvic/

**Comment by sorgelig** [comment]
i can update the palette but i don't see table of values for new colors.

**Comment by rsn8887** [comment]
Updated palette from https://www.pepto.de/projects/colorvic/ 
![](https://www.pepto.de/projects/colorvic/vic2.png)

hex 
00, 00, 00
FF, FF, FF
81, 33, 38
75, CE, C8
8E, 3C, 97
56, AC, 4D
2E, 2C, 9B
ED, F1, 71
8E, 50, 29
55, 38, 00
C4, 6C, 71
4A, 4A, 4A
7B, 7B, 7B
A9, FF, 9F
70, 6D, EB
B2, B2, B2

decimal
0, 0, 0
255, 255, 255
129, 51, 56
117, 206, 200
142, 60, 151
86, 172, 77
46, 44, 155
237, 241, 113
142, 80, 41
85, 56, 0
196, 108, 113
74, 74, 74
123, 123, 123
169, 255, 159
112, 109, 235
178, 178, 178

The old palette currently used by the core is the Pepto-Pal palette from https://www.pepto.de/projects/colorvic/2001/
00 00 00
FF FF FF
68 37 2B
70 A4 B2
6F 3D 86
58 8D 43
35 28 79
B8 C7 6F
6F 4F 25
43 39 00
9A 67 59
44 44 44
6C 6C 6C
9A D2 84
6C 5E B5
95 95 95

**Comment by sorgelig** [comment]
Yeah, i've used photoshop to get hex values from that colored stripe. Just wanted to know if picture represents originally calculated values not altered in any graphical editor/compressor.

**Comment by rsn8887** [comment]
Yes those are the correct numbers, they also appear in WinVice emulator if you select colodore there.

**Comment by rsn8887** [comment]
The NES core has what seems to be the most comprehensive palette options. There are several presets to choose from, and also a choice „custom“ which allows a user-defined palette to be loaded. Maybe the code from the NES palette option could be re-used here?

**Comment by sorgelig** [comment]
As i've said before there is no reason to make a Christmas Tree from all cores. C64 had quite fixed colors and it must be used. If there is a errors, then i'm ready to fix it.

**Comment by rsn8887** [comment]
Then I would say it is best to update to latest known correct most accurate colors, which are the ones I listed above from https://www.pepto.de/projects/colorvic/

**Comment by rsn8887** [comment]
I made a PR. Thanks for considering this!

**Comment by rsn8887** [comment]
Fixed in release 20210117. Thanks!
