### ISSUE TITLE
Left and right borders are cut

### ISSUE THREAD

**Issue by sasq64** [MiSTer-devel/C64_MiSTer#57]
Left and right borders are not fully shown, but become black at the very edges

This is more noticeable on monitors that shows more overscan, like the 1084.

![PXL_20210118_131750664](https://user-images.githubusercontent.com/531713/104920631-5ae83300-5998-11eb-9091-1c3ca7223dc4.jpg)

![PXL_20210118_131720059](https://user-images.githubusercontent.com/531713/104920644-60de1400-5998-11eb-866f-e797f0a3be49.jpg)

**Comment by rsn8887** [comment]
I can confirm this also via HDMI:
![IMG_3012](https://user-images.githubusercontent.com/13071547/105639334-56f75d80-5e3d-11eb-8676-f0c65fc90ab5.jpg)

It can be reproduced with this freeware game:
https://csdb.dk/release/?id=198593

**Comment by sorgelig** [comment]
border is tuned for HDMI output to keep paper area large enough

**Comment by rsn8887** [comment]
Thank you for the awesome work, fixed in latest release 20210521:
![IMG_4347](https://user-images.githubusercontent.com/13071547/119211498-12d93a00-ba78-11eb-9a86-1817f08f70fa.jpeg)

**Comment by sasq64** [comment]
![20210522_214718](https://user-images.githubusercontent.com/531713/119249559-b2dab480-bb99-11eb-8bfc-6bbe84258b70.jpg)
Looks good on CRT also!

**Comment by sorgelig** [comment]
good!
