### ISSUE TITLE
Say it program SAM

### ISSUE THREAD

**Issue by Televicious** [MiSTer-devel/C64_MiSTer#60]
Weird issue with the sid chip. I tried the SAM.d64 and the guten tag voice works if you run the first program, but it you run say it where it recites everything you type it blips out a sound and doesn't actually speak the whole line.

**Comment by Televicious** [comment]
Also the vicious sid demo only the first two tracks play. After that it is silence.

**Comment by raparici** [comment]
> Also the vicious sid demo only the first two tracks play. After that it is silence.

The silence is during the VIC trick only. The demo actually runs flawlessly, sound coming from VIC like rest of the background noise is not emulated. As the demo specifies that sound is not generated by the SID and afaik is not emulated in other fpga implementations neither emulator. It is not a core issue, maybe something to consider for the future, though maybe it will be something that will stay in the real of the real machines like the background sound they emit. I think the issue should be closed.

**Comment by sorgelig** [comment]
That VIC sounds is just a proof how bad C64 was shielded inside against different parts of circuit. I'm sure you don't want to hear the noise from video chip while playing games as it's something should be avoided in well designed HW. Making an option just for a single demo is silly. 
So i don't think it worth to implement.
Original issue with SAM is not an issue as explained above. Just matter of correct mode switch.
