### ISSUE TITLE
MIDI->TCP UART option gone?

### ISSUE THREAD

**Issue by neutralinsomniac** [MiSTer-devel/C64_MiSTer#62]
On the previous core version, I could select UART mode MIDI, and change the Connection to TCP. Now it looks like only UDP and Local are available options. Did something change in how we’re meant to set up the UART Hayes modem simulator for TCP?

**Comment by neutralinsomniac** [comment]
gah. Apparently this is an issue with the MiSTer_MidiLink core, not your core. Hrm. Sorry for the noise.

**Comment by jstavats** [comment]
for more details see here. https://misterfpga.org/viewtopic.php?f=27&t=375&start=50
