### ISSUE TITLE
Feature Request: SID chip revision option

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/C64_MiSTer#63]
There were several revisions of the SID 6581 sound chip which sounded different.

For example, the R4 revision had an echo effect that was more pronounced than on other revisions.
Demo:
Geir Tjelta - Echoes (6581R4)
https://www.youtube.com/watch?v=urMw_xwY24E

It would be cool if all the revisions could be implemented and the user allowed to choose chip revisions. I don't think any emulator does this yet?

Thanks to v3to for telling me about this.

**Comment by MJY71** [comment]
By the way, that is specifically the 6581R4**AR** revision, not just the R4. The commonly held belief is that the 'AR' stands for 'Advanced Resonance'. It is my favorite sounding 6581 by a long shot.

**Comment by sorgelig** [comment]
No problem. You are free to implement more SID filters in HDL and make pull request. 
It's not that someone doesn't want to add it. 
I don't see point of this issue.

**Comment by sorgelig** [comment]
it's implemented through loadable filter curve.
