### ISSUE TITLE
HDMI video issues 20210216 

### ISSUE THREAD

**Issue by 0xc0ffea** [MiSTer-devel/C64_MiSTer#65]
Testing on 20210216 
vscale_mode=0
Video Standard :PAL
Aspect Ratio :Original

Vertical Crop : Yes - breaks all Scandoubler Fx (same for ZX Spectrum Core)

Horizontal pixel march / shimmer effect in scrolling games in all modes, well demonstrated in "Batman - The Movie (1989) (Ocean Software)"  CRT version (TOSEC). Start game and move batman left and right, watch background bricks.

Appears the horizonal resolution is incorrect when Vertical crop is enabled, the vertical resolution is incorrect when Vertical Crop is disabled. (this also affects the ZX Spectrum core, See play area border on Dizzy2)

Vertical Crop is not disabled starting the core with ini vscale_mode=1 - the core starts in vcropped mode and then corrects itself when any of the options are changed. Incorrect screen pixel dimensions still present.

Zoom aspect ratio has vanished.

**Comment by sorgelig** [comment]
> Vertical Crop : Yes - breaks all Scandoubler Fx (same for ZX Spectrum Core)

yes. This is expected.

> Horizontal pixel march / shimmer effect in scrolling games in all modes, well demonstrated in "Batman - The Movie (1989) (Ocean Software)" CRT version (TOSEC). Start game and move batman left and right, watch background bricks.

Use video filter to eliminate shimmering. Lanczos filters should eliminate shimmering. Also higher HDMI resolutions reduce shimmering.

> Appears the horizonal resolution is incorrect when Vertical crop is enabled, the vertical resolution is incorrect when Vertical Crop is disabled. (this also affects the ZX Spectrum core, See play area border on Dizzy2)

I don't get it. Show screenshots may be.

> Zoom aspect ratio has vanished.

it's converted to Vertical crop option.

**Comment by sorgelig** [comment]
HV-integer scale is implemented.
Cropped video keeps the aspect ratio since several releases back.
