### ISSUE TITLE
Quickformat (N0:name) works, but long format (N0:name,id) causes 21,READ ERROR,0,0

### ISSUE THREAD

**Issue by verm71** [MiSTer-devel/C64_MiSTer#67]
With various utilities, wedges, and even native basic commands, doing a long format fails. Some games and utilities format their own data disks and this also fails. Quick format by specifying only the disk name succeeds, as this only re-writes track 18.

**Comment by vpelletier** [comment]
This is because the conversion from D64 format to the drive-internal bit stream peeks at the directory to know the disk name to put in the reconstructed sector headers. This knowledge is only updated when loading a new disk, so formatting only works if it keeps the same disk id.

**Comment by verm71** [comment]
Just wanted to circle back and say that it's been fixed in 20210617!  Both D64 and G64 format successfully with full format! (At least under JiffyDOS... stay tuned for more thorough testing...)

**Comment by sorgelig** [comment]
yep, as mentioned in release info.
