### ISSUE TITLE
Feature Request: Add Zoom mode back to the core.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/C64_MiSTer#68]
I recently noticed that the Zoom mode has been removed, or at least I can no longer find it.  

I'm very happy to see 5x vertical crop implemented, but some games can really benefit with the original zoom mode that the core use to offer since it can scale the image much bigger than 5x crop does.   I hope someone will reimplement that mode since it does have its own benefits.  5x crop is indeed a nice feature, but it shouldn't be considered a full replacement for the original Zoom mode. Thanks

**Comment by SegaSnatcher** [comment]
There should be some kind of option so we can fill the 200p graphics area fully vertically, because games are still scaled very small even when 5x crop is enabled.  I guess a remove borders option would be what I'm talking about like we have on SMS.

**Comment by sorgelig** [comment]
well.. for 1080p it's possible to use 216 lines instead of 270.. i will think about it

**Comment by SegaSnatcher** [comment]
Thanks

**Comment by SegaSnatcher** [comment]
Just some adding input.  I think the current crop mode works great in NTSC mode for C64, but its PAL mode where I think more vertical scaling would really benefit since PAL has a thicker vertical border than NTSC.

**Comment by sorgelig** [comment]
because 270 lines used in PAL is more than NTSC has. So NTSC uses 216 lines for integer scaling.

**Comment by sajattack** [comment]
I thought it was replaced by the custom aspect ratio option.

**Comment by SegaSnatcher** [comment]
> I thought it was replaced by the custom aspect ratio option.

Custom aspect ratio only deals with horizontal scaling.   Zoom mode scaled the image larger vertically.

**Comment by SegaSnatcher** [comment]
Just tested the new 216 crop mode, works great.  Thanks Sorg!!!
