### ISSUE TITLE
PAL video issue on Release 20190111

### ISSUE THREAD

**Issue by bedfelllow** [MiSTer-devel/C64_MiSTer#7]
Release 20190111 appears to have introduce a video bug whereby in PAL video standard there is a  vertical line to the right of the display in all Scandoubler Fx modes other than HQ2x-320.

This can be seen as a green line in the image linked below:

![20190111_183125](https://user-images.githubusercontent.com/20281271/51053980-33a14300-15d3-11e9-9ed1-3b3424ead7fb.jpg)

**Comment by verm71** [comment]
Also noticed that CRT scanlines don't seem to line up as well as they used to in the previous version. Related?

**Comment by sorgelig** [comment]
scanlines are not related to the issue - it's intended feature. Since new scaler can use near neighbour scaling, scanlines won't look good. So, scanlines are bound to output resolution. 
You can use scaler filters with scanlines effect as well.

**Comment by sorgelig** [comment]
i will fix the issue

**Comment by sorgelig** [comment]
fixed
