### ISSUE TITLE
Stereo and mono with same SID chip both right and left sounds too differently

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/C64_MiSTer#72]
There seems to be something wrong with the SIDs

When you use the same SID chip in both channels (same address) they should sound the almost same (perhaps apart from the noise) and therefor there should be no or little change in the sound when you change the Stereo mix from None to 100% - but there is.

Could one of the channels be delayed by mistake? - or perhaps inverted?

**Comment by sorgelig** [comment]
If you start to change one SID then it may get some additional change/delay against other SID. So set 2 SIDs identically, save settings and then reload the core.

**Comment by dfilskov** [comment]
Ah yes - that makes sense. I'll check with save and reload.

**Comment by dfilskov** [comment]
You were right - I needed to reload the core. Thanks!

**Comment by sorgelig** [comment]
you may change SID type and Filter type without loosing the sync. You will loose sync if you will change address of second SID because it may miss some writes.
