### ISSUE TITLE
Please add 'None' as right SID chip option so you can use just one SID chip - not two

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/C64_MiSTer#73]
It seems hard or perhaps impossible to just use one SID chip - like in a real C64 - in mono.

The best option is to set Right channel to another address and then Stereo mix to 100% - oddly enough  it still seems to produce a stereo signal at Stereo Mix: None even though there should be sound only in the Left channel, right?

**Comment by sorgelig** [comment]
if two SIDs are the same with same address then they will sound identically, so it will be the same as mono -> same as real C64.

**Comment by dfilskov** [comment]
That's what I expected but have you checked that the signal infact becomes mono? - after save settings and reset - or perhaps core reload I mean. I'll test now.

**Comment by dfilskov** [comment]
Yes, when you reload the core it works nicely! Thanks :) - I've found another SID issue, though, that I will report now.
