### ISSUE TITLE
The SID filter seems to be inverted

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/C64_MiSTer#74]
It doesn't happen when you use just one of the chips - but if you run both simultaenously the filtered SID channel seems to disappear. This makes me suspect that the filter is inverted in one channel or chip but not the other.

Please listen to this test (I've included the PRG file double density):

https://www.dropbox.com/sh/8nnxavyaxdu8v59/AABrwJkWNKBBMLg22YqmVHh6a?dl=0

**Comment by dfilskov** [comment]
It's also easy to hear when using an 6581 with the 8580 filter simultaeously with the 8580 like this:

![filter maybe inverted](https://user-images.githubusercontent.com/15096058/114378786-55aa1700-9b88-11eb-90af-86de3faf3987.png)

I tested with the PRG file 'eternal' for this screenshot. It's also included in the link above now.

**Comment by sorgelig** [comment]
6581 and 8580 implementation use different modules and they may have some pros and cons each one, that's why you have selection. None is perfect.
Also 8580-like filter on 6581 module is NOT supposed to be fully matched to 8580. Even real 8580 has some difference from 6581 regardless the filter.

**Comment by dfilskov** [comment]
After today's release - thanks a lot! :) - it's changed ... this time the filtered channel does not disappear - the OTHER channels disappear when you set Stereo mix 100% using two different SIDs :)

Here I'm demonstrating it using Double density.PRG
https://www.dropbox.com/s/1gev4vr970o89p4/SID%20filter%20channel%20still%20inverted.mp4?dl=0

I think this is what's is going on:

In the earlier build when you mixed two different SIDs the filtered channel disappeared. A likely explanation would be that one of the SID's filter (everything that went through that SID's filter) was inverted. E.g. like this (one single sample output - simplified since time / the waveform is of importance):

Earlier build:

6581
ch 1 = 5
ch 2 = 5
ch 3 filtered = 5
(15 total)

8580
ch 1 = 5
ch 2 = 5
ch 3 filtered = -5 (inverted)
(15 total - since channels don't cancel each other out unless the play exactly or almost the same)

When mixed this would give this output

6581 + 8580:
ch 1 = 5
ch 2 = 5
ch 3 filtered = 0
(10 total - ch3 is missing since it's filtered)



In the latest build 2021-04-06 the entire left or right channel (or the entire output of of the SIDs) has been inverted.
This will explain why it's now the opposite of before. Like this:

build 20210416 

6581
ch 1 = -5
ch 2 = -5
ch 3 filtered = -5
(-15 total)

8580:
ch 1 = 5
ch 2 = 5
ch 3 filtered = -5
(15 total - since channels don't cancel each other out unless the play exactly or almost the same)

When mixed:

6581 + 8580:
ch 1 = 0
ch 2 = 0
ch 3 filtered = -10
(-10 total - ch1 and 2 are missing since it's filtered)




The solution is to simply invert the filter in one of the SIDs ... that would give this result:

6581
ch 1 = 5
ch 2 = 5
ch 3 filtered = 5
(15 total)

8580:
ch 1 = 5
ch 2 = 5
ch 3 filtered = 5
(15 total)

When mixed:

6581 + 8580:
ch 1 = 10
ch 2 = 10
ch 3 filtered = 10
(30 total - ch1 and 2 are missing since it's filtered)

It's a simpified example but I hope it makes some sort of sense.

Since all channels can go through the filter in the SID, I think, we can find a piece of music - or I could simply make one - where ALL three channels go through the filter and this would give almost total silence when mixing the two SIDs. Therefor we should make sure that the filter has the same phase (not opposite) on the two difference SIDs.

**Comment by sorgelig** [comment]
try this:
[C64.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6329136/C64.zip)

**Comment by dfilskov** [comment]
PERFECT! - good work - thank you so much! :)
