### ISSUE TITLE
Problems with Load/Auto-Run Certain PRG Files

### ISSUE THREAD

**Issue by MJY71** [MiSTer-devel/C64_MiSTer#77]
There is a version of the High Voltage SID Collection (HVSC) that has been converted in its entirety to PSID64 PRG files, which has been great for the C64 MiSTer core since there is no mass storage option to be able to browse the original collection from within a native SID player program.

https://hvsc.c64.org/downloads

These PRG files used to load with no problems in previous releases. However, with release 20210423, they no longer appear to load or auto-run at all when selected through the `Load File *.PRG` OSD option.

**Comment by sorgelig** [comment]
i'm not sure what are you talking about. HVSC collection is set of separate SID files and several disk files.
I don't see PRG files in collection.

**Comment by MJY71** [comment]
Like I said, there is a version that has been converted to PRG files. From that download link above:

"Zero-X kindly converted HVSC to PSID64 files, so you can playback the tunes on your C64 or via cartridges like the 1541 Ultimate, MMC64, MMC-IEC, SD-IEC or whatever these new fashioned gadget are called these days. [Get it here!](https://boswme.home.xs4all.nl/HVSC/HVSC74_PSID64_packed.7z) (144 MB)"

**Comment by sorgelig** [comment]
in the meanwhile i've identified the problem. will fix it.

**Comment by MJY71** [comment]
Thank you very much sorgelig. I really appreciate it. Thank you for all you've done and continue to do.

**Comment by MJY71** [comment]
Everything appears to be working perfectly again. Thank you!
