### ISSUE TITLE
Black screen (crt games)

### ISSUE THREAD

**Issue by kaloun34** [MiSTer-devel/C64_MiSTer#78]
Hello,

Since this last update, some games no longer want to work (black screen). Ex: "Green beret"

**Comment by sorgelig** [comment]
are there other non-working CRT games? i don't have this game.

**Comment by kaloun34** [comment]
Yes !  Commando,  black screen also
I retested with the previous version and these games work fine

**Comment by sorgelig** [comment]
Commando works ok.

**Comment by kaloun34** [comment]
I deleted my configuration file and put the same configuration back!
And it works ! 
I don't understand ... Sorry ...

**Comment by sorgelig** [comment]
if it's solved, then close the issue please.

**Comment by kaloun34** [comment]
ok

**Comment by kaloun34** [comment]
delete the file /Config/C64.cfg and it's good

**Comment by sorgelig** [comment]
You can do the same from OSD: Reset Settings. Then Save settings.
