### ISSUE TITLE
PRG autorun

### ISSUE THREAD

**Issue by tehashen** [MiSTer-devel/C64_MiSTer#79]
Hi,
Since the 20210424 release, the fix for PRG autorun works too well.
We can’t configure sidplay64 for the second SID anymore.

**Comment by MJY71** [comment]
That's interesting. I know this doesn't involve SIDPLAY64, but the PSID64-converted HVSC .PRG files work properly now after that fix. I am able to change the memory address for the second SID for all of the 2SID files in that collection with no problem.

If you're using SIDPLAY64, you shouldn't even be using .PRG files. It plays .SID files directly. I don't think .PRG files are even supported with that program.

**Comment by sorgelig** [comment]
I even don't know how core can affect configurability of specific program.
SIDs are on the same addresses as before, so probably it's not related to MiSTer. Or may be that player never worked before too.

**Comment by tehashen** [comment]
> That's interesting. I know this doesn't involve SIDPLAY64, but the PSID64-converted HVSC .PRG files work properly now after that fix. I am able to change the memory address for the second SID for all of the 2SID files in that collection with no problem... not to suggest that changing the second SID address was a problem before the fix. Those simply wouldn't run after loading, even after typing 'RUN', instead displaying PETSCII symbols as the letters were typed.
> 
> If you're using SIDPLAY64, you shouldn't even be using .PRG files. It plays .SID files directly. I don't think .PRG files are even supported with that program. It's the program I use the most on real hardware and 1541U2+ cartridge.

I start SIDPLAY64 by launching the PRG and it goes to read the SID on a disk. But since the 2 last releases, I can’t have the settings at startup

**Comment by tehashen** [comment]
> I even don't know how my changes may affect configurability of specific program.
> SIDs are on the same addresses as before, so probably it's not related to MiSTer. Or may be that player never worked before too.

with the 20210416 release, I have to configure some settings after launching the program 
![621E9628-6B79-45CA-A9DC-ED4DB9F50D50](https://user-images.githubusercontent.com/67312247/116271148-023aea00-a780-11eb-913e-65bb7547c62f.jpeg)

Since the fix, the settings page passes very fast.

To be fair, this isn’t a big issue for me. I used to use SIDPLAY64 on the Ultimate64 with real SID.
I just wanted to test some SID since the recent updates you made.
By the way, the updates are amazing. The emulated SID on the MiSTer are far better than the one on the U64.

**Comment by tehashen** [comment]
Just a short video to show what's happening since the fix
https://youtu.be/rQRHDRl9zBk

**Comment by MJY71** [comment]
> Just a short video to show what's happening since the fix
> https://youtu.be/rQRHDRl9zBk

Ahh, okay. I see what you mean now. That is strange... almost like the Enter/Return key is held down as the program launches, breezing right past all those prompts.

**Comment by sorgelig** [comment]
can i get such PRG?
probably it's related to autotyped RUN<enter>

**Comment by tehashen** [comment]
> For what it's worth, SIDPLAY64 is my go-to on the Reloaded MK2 w/ 1541U2+, hands down. It's a fantastic application. But on MiSTer, it's a bit limited without mass storage support to be able to browse the entire collection like on real hardware.
> 
> For MiSTer, I use the version of the HVSC collection that has been converted to PRG files, where each file contains its own PSID64 player (link is on the HVSC download page). That way I'm able to browse the entire collection through the OSD. While not as effortless as browsing from within SIDPLAY64, it is a good option... and at least the OSD remembers the last file selected to minimize re-navigating the entire collection from square one when you want to select another track from the same artist. Have you tried those?

I just wanted to compare the sound on the MiSTer with the same tool I used on the U64 :-)

Here the PRG to test
[sidplay64-normal.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6386999/sidplay64-normal.zip)

**Comment by sorgelig** [comment]
try this:
[C64.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6387024/C64.zip)

**Comment by tehashen** [comment]
It works again.
Thanks Sorgelig!

**Comment by MJY71** [comment]
Confirmed that the build attached is working as expected for me as well. That was a strange issue, the way it not only quickly skipped past all those initial prompts (choosing the defaults), but continued to do so once it got to the main screen. The disk activity light would constantly flash as though it was searching for media files without being prompted to do so.

Thank you for the fix once again, sorgelig. These little issues must be really frustrating.
