### ISSUE TITLE
Request for email from main C64 keyboard person(s)

### ISSUE THREAD

**Issue by Perifractic** [MiSTer-devel/C64_MiSTer#80]
Hello, Perifractic here from YouTube channel Perifractic's Retro Recipes (http://youtube.com/perifractic). Firstly thank you for your incredible contribution to the retrocomputing community, and for keeping the happiness of childhood nostalgia alive for so many people who can’t afford / don’t have space / prefer not to use real C64 hardware. I'm a fan.

I have a slightly confidential need to chat with the "key person(s)" on the C64 branch of this project, about keyboard mapping. If you are reading this please kindly email me via the link at the bottom of http://perifractic.com/contact and I'll be delighted to explain further.

Thanks and keep up the great work.

Your friend in retro, Perifractic

**Comment by sorgelig** [comment]
i've sent email.
Since it's not an issue, i close it.
