### ISSUE TITLE
Line Noise using UART Modem

### ISSUE THREAD

**Issue by Commodork** [MiSTer-devel/C64_MiSTer#81]
I am getting line noise (random garbage characters) when using the UART modem and connecting to BBSes. The random characters happen both when reading remote text, and when typing locally to send text. See the bottom line of text in the attached screenshot as an example.

Core version: 210426
Settings on the core: User Port: UART / UART Connection: Modem / Link: TCP / Baud: 2400

I have tried connecting to multiple BBSes and get random garbage characters on all of them. My MiSTer is connected to my home router via ethernet (no WiFi). I have tried multiple term programs, including CCGMS 2021 and Striketerm 2014. 

I would be glad to report any settings or test anything you want. My INI has never been manually modified.

![2021-04-28 09 56 07](https://user-images.githubusercontent.com/23263961/116588336-0cc0c500-a8e1-11eb-8296-8a6ce4a49767.jpg)

**Comment by sorgelig** [comment]
was it improved in latest release?

**Comment by Commodork** [comment]
The problem still exists in v210509. I have mentioned this to a couple other people using the modem option on the C64 core and they are seeing the same errors.

**Comment by sorgelig** [comment]
try both PAL and NTSC modes. May be terminal app is tuned to specific TV mode.

**Comment by Commodork** [comment]
I just downloaded and tried v20200122 with the same settings (2400) and the problem does not happen. 

Immediately switched back to the latest core, same settings and same term program, and the problem happens.

**Comment by sorgelig** [comment]
can you try builds between v20200122 and latest to find a first problematic?

**Comment by sorgelig** [comment]
may be you need to teach me how to setup BBS connection. Which aplication do you use? What is the settings, and what is the address of BBS. I will try to connect myself.
Also how to reproduce the problem.

**Comment by Commodork** [comment]
So, inside the C64 core you need to have the following settings:

_OSD > System > Expansion: UART
OSD > UART Mode: Connection: Modem
OSD > UART Mode: Link: TCP
OSD > UART Mode: Baud: 2400_

Next you need a term program that supports telnet. The most common one is CCGMS 2021.
Link: [https://csdb.dk/release/?id=198392](https://csdb.dk/release/?id=198392)

After loading CCGMS 2021, hit F7 and make sure you have the following settings:

_Baud Rate: 2400
Modem: User Port 300-2400
Firmware: Standard_

From the terminal, you can "dial" any BBS. You can get a list of C64 BBSes from the following site:
BBS List: [http://cbbsoutpost.servebbs.com/](http://cbbsoutpost.servebbs.com/)

I did a quick test with the first BBS on the list. To dial, type adtd (lower case) and the URL with no space in between, followed by a colon and the port. Example:

atdt13th.hoyvision.com

The that older core I tried, everything will work fine. On the newer versions of the core, there will be a lot of garbage that appears on the screen. I will do some testing and try to narrow down exactly which version of the core introduced the error.

**Comment by sorgelig** [comment]
Striketerm 2014 it seems the best C64 term. It works in PAL mode and uses its own RS232 routines, so can work even with JiffyDOS and DolphinDOS where serial port isn't supported in kernal.

Also i've added HW flow control signals and garbage disappeared.

**Comment by sorgelig** [comment]
wait for my fix. C64 needs HW flow control to work correctly

**Comment by sorgelig** [comment]
[C64.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6462700/C64.zip)
this version has HW flow control.
standard 2400 mode looks fine. It also supports UP9600 (when 9600 baud rate is selected in UART mode), but it seems even with HW flow control it still fails sometimes.

**Comment by Commodork** [comment]
Sorgelig, you've done it again -- this build works perfect. Confirmed with both Striketerm and CCGMS 2021. No line noise on either at 2400 baud.

**Comment by sorgelig** [comment]
released.
Note, Striketerm 2014 doesn't work good on 9600 mode. It seems doesn't use HW control even if enabled in advanced options. 
CCGMS Ultimate (not 2021!) version now is the best terminal. It works with UP9600 with up to 9600 baud without corruptions.
