### ISSUE TITLE
MiSTer C64 core faster than real or emulated C64? 

### ISSUE THREAD

**Issue by tehashen** [MiSTer-devel/C64_MiSTer#82]
Hi,

I don't know if this is a real problem, but I noticed some strange behavior from the C64 core. 
Yesterday I ran tests with the Dead Test 781220 cartridge on all C64s I have (real C64, MiSTer C64 core, MiST C64 core, C64 Reloaded mk2, Ultimate64 and Vice). 
All of them finished the first cycle in 1 minute 15 seconds 
![Other](https://user-images.githubusercontent.com/67312247/116909465-8986d280-ac44-11eb-8c27-554decebd25c.jpg)

except the MiSTer's C64 core which does it in 1 minute and 13 s
![MiSTer](https://user-images.githubusercontent.com/67312247/116909795-02862a00-ac45-11eb-85c9-c67b10fe6617.jpg)

All are configured in PAL and with the stock kernal.

Here the cartridge 
[c64-diag-dead-test-rev-781220.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6416508/c64-diag-dead-test-rev-781220.zip)

**Comment by sorgelig** [comment]
even MiST version finishes in 1.15?

**Comment by tehashen** [comment]
Yes, the first picture shows the output of the MiST core.
I thought the 2 cores shared the same base code.

**Comment by sorgelig** [comment]
Not fully the same. Core doesn't work faster. It's TOD clock not correct. I will fix it in next release.

**Comment by tehashen** [comment]
Ok, thanks!
I'll close this issue.
