### ISSUE TITLE
[Regression] Floppy Drive not working

### ISSUE THREAD

**Issue by tomaszb-dev** [MiSTer-devel/C64_MiSTer#83]
Mounted images does not load. Implemented device stop at searching while command load"$",8 or load"*",8,1. Implemented C64 core then hangs. Same behavior without mounted image.

**Comment by sorgelig** [comment]
I don't see such behavior. Except fastloder form action replay, everything else works.
fastloader will be fixed soon.

**Comment by lanedenson** [comment]
I am experiencing the same thing, regardless if I have a Loadable C64 or Standard C64 selected.

**Comment by lanedenson** [comment]
Still having the same issue after updating to today's release

**Comment by Commodork** [comment]
I am having the same issue. I tried first with Epyx Fast Load, and then without it.

**Comment by sorgelig** [comment]
try to reset the settings then save settings.
It's something very specific to your config/setting. If it wouldn't really work then everyone would have problems.

**Comment by sorgelig** [comment]
just tried Epyx Fast Loader - works fine. With DolphinDOS parallel mode i have no idea who needs those fast loaders - they are like 10x slower than Dolphin.

**Comment by Commodork** [comment]
I reset all settings and detached all cartridges. Any debug logs I can provide?

https://www.youtube.com/watch?v=0Vcw_nEiVGQ

**Comment by sorgelig** [comment]
Show me OSD->Hardware page settings
I've just discovered that if you choose Loadable C64 system ROM but didn't load any ROM then it will behave that way. 
Choose "Standard C64" ROM (and then reset the core)

**Comment by Commodork** [comment]
That's it! Changed to standard and it's working.

**Comment by lanedenson** [comment]
Same here - resetting the settings and selecting Standard C64 did the trick.  Thanks!

**Comment by sorgelig** [comment]
Try this build, it should fix the issue as well:
[C64.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6431193/C64.zip)

**Comment by sorgelig** [comment]
should be fixed in new release
