### ISSUE TITLE
loadable ROM not loading

### ISSUE THREAD

**Issue by ch570512** [MiSTer-devel/C64_MiSTer#84]
Hello

Since the last update, ROMs are not loaded from "boot.rom" anymore.

Greetings
Thorsten

**Comment by sorgelig** [comment]
Because boot.rom isn't used anymore. Use OSD option in hardware page to choose the ROM.

**Comment by sorgelig** [comment]
For historical reason MiSTer hides boot.rom from selection. But you can give some real name instead of boot.rom

**Comment by ch570512** [comment]
Good info. :) Thank you! Really appreciate your work
