### ISSUE TITLE
Feature Request: ADC Support

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/C64_MiSTer#86]
Would it be possible to add ADC support to the core?

**Comment by sorgelig** [comment]
external tape input for C64/C16/VIC20 is problematic as computer controls the motor of tape player. Without control of player computer will miss the data.
There is already tape player integrated which is pretty much the same and additionally it's controlled by computer and gives full emulation of tape player.

**Comment by sorgelig** [comment]
i close this as "impossible to implement".
