### ISSUE TITLE
After new PRG loading system (May 4 Update), all freezers are broken

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/C64_MiSTer#87]
Following the update of May 4, when implementing that the machine is reset when executing a .PRG it is impossible to use any freezer such as Action Replay, Final Cartdridge, etc, since when resetting the core, it reloads the cartridge, and PRG is not loaded., making any cartridge for debugging, infinite lives, etc. totally unusable.
Is it possible to return to the situation before this update?

**Comment by sorgelig** [comment]
i will add an option to not reset.

**Comment by sorgelig** [comment]
added an option.
