### ISSUE TITLE
1541 compatibility regression

### ISSUE THREAD

**Issue by juri74** [MiSTer-devel/C64_MiSTer#88]
Hi
The game Turrican 3 with latest core version display " ! DISKERROR ! " message during loading and do not load anymore.
I tried all possible combinations (with or without dolphindos, user port set to joystick and not to floppy disk) but i still get the error.
i did a quick test with an old core i have on another sdcard version 21.01.17 and it is working. 
Thanks.

**Comment by sorgelig** [comment]
fixed.
