### ISSUE TITLE
Function Request : G64 files

### ISSUE THREAD

**Issue by lroby74** [MiSTer-devel/C64_MiSTer#89]
Would be very nice talking about preservation is FPGA C64 may support G64 files that are exact copies of original floppy disks

**Comment by sorgelig** [comment]
it's supported now if we are talking about exact copy of tracks.
Protected disks may not work but that is due to a precise disk timings emulation which is another story.

**Comment by lroby74** [comment]
> it's supported now if we are talking about exact copy of tracks.
> Protected disks may not work but that is due to a precise disk timings emulation which is another story.

Thank you very much, this is a dream came true!
