### ISSUE TITLE
Pal video mode in 15khz does not fill the whole screen

### ISSUE THREAD

**Issue by mabrilG** [MiSTer-devel/C64_MiSTer#9]
I tried the Pal video mode in 15khz and the border does not fill the whole screen. The aspect ratio configuratión is in original, maybe the values ​​of HBlank or VBlank is not correct.
It is not caused by the geometry of television, the C64 core in Mist does it correctly and it looks good expanded.
Thanks

**Comment by Titofff** [comment]
Hello.
I see the same thing, the screen is off-center. Would it be possible to propose a possibility to frame the right and the left  or center the screen ? It will be perfect !

**Comment by mabrilG** [comment]
In the new release 20200430 with PAL hblank ajustement the image is center.
I close the issue.
