### ISSUE TITLE
C64 Core. Custom High Res node not work

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/C64_MiSTer#91]
Hi, i run a .prg file from last Tramsmission64 party in c64 core and screen go black.
I tested it in LCD and CRT.
The program in question is https://csdb.dk/release/?id=203356
[02 butt n cock ext.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6471491/02.butt.n.cock.ext.zip)
I run it in c64c, and Ultimate64 perfectly.
I use official Mister from manuferhi.

From de original post in csdb "The mode (and also the making) of this pic is kind of custom, with hires and laced sprites, sprites being partly on the hires, partly behind some tones. This to decrease the flickering. It sure flickers a lot less than our earlier pics in this direction. I've as well tried to use less 'traditional' 01010… -dithering."

**Comment by sorgelig** [comment]
i think the problem happens before the picture, that's why it's black. Otherwise some at least corrupted pic should appear.
Source code of such prg would help.

**Comment by makigumo** [comment]
Seems to work fine on latest release 20221007. So can probably be closed.
![20221030_185558-butt n cock ext](https://user-images.githubusercontent.com/565430/198893706-b57a272b-4b5a-4e62-8144-800eb690eccc.png)
