### ISSUE TITLE
C64 Disk writing, D64 image size / corruption issue?

### ISSUE THREAD

**Issue by r3mowilliams** [MiSTer-devel/C64_MiSTer#92]
I was playing Autoduel a bit on the core (which writes fairly frequently to disk to save/update your character) and went to load the same D64 images in Vice and it refused to mount the second disk.

Looking at the size of the second image it has rather unexpectedly grown in size, which was why Vice wouldn't mount it, and showed the image as corrupt.  I don't recall ever a D64 image growing in size like this in any past emulator.

I have been testing this in Vice with a clean image set (using both Jiffydos and Dolphindos2), and have not experienced this issue.

```
 Directory of \\mister\fat\games\C64\Autoduel

05/18/2021  03:57 PM    <DIR>          .
05/17/2021  06:50 PM    <DIR>          ..
05/17/2021  02:35 PM           174,848 Autoduel Disk 1.d64
05/18/2021  12:09 PM           177,152 Autoduel Disk 2.d64
```

**Comment by sorgelig** [comment]
I guess it's not corruption but some issue related to how disk get written to SD card. Does it still work in MiSTer?

**Comment by r3mowilliams** [comment]
Yes the oversized Disk 2 does seem to still function in MiSTer, just no longer anywhere else.

**Comment by r3mowilliams** [comment]
current extraneous data beyond the normal disk image end in Disk 2

https://imagizer.imageshack.com/img924/230/l3Tq3w.jpg

**Comment by verm71** [comment]
In Vice, you may have to enable "True Drive Emulation" in case your Disk 2 has had some additional tracks written to it, beyond the standard 35 (just guessing here).

**Comment by sorgelig** [comment]
it wasn't additional track, but just "tail" of aligned size. 
Anyway, it was fixed several releases ago in Main.
