### ISSUE TITLE
Tape loading broken since release 20210529

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/C64_MiSTer#94]
On current release loading a .TAP file with standard KERNAL halts the computer. Instead of starting to load the tape C64 gets stuck on empty light blue screen. Enabling tape sound reveals total silence instead of expected program noise. Green LED on the I/O board keeps flashing signifying loading despite nothing actually happening.
This issue is not present in release 20210525, leading me to believe that tape loading got broken in 20210529 (where this issue is present).

**Comment by sorgelig** [comment]
try this build:
[C64.zip](https://github.com/MiSTer-devel/C64_MiSTer/files/6567264/C64.zip)

**Comment by NML32** [comment]
@sorgelig the test build you posted above works, I can now successfully load TAP files. I was experiencing the same issues loading TAP files that @Thelypody reported. 
Thank you.

**Comment by Thelypody** [comment]
@sorgelig Sorry for the delayed response, just tested your attached build. Tape loading works properly now.
Thanks.
