### ISSUE TITLE
C64 Tape Loading bug & Request. 

### ISSUE THREAD

**Issue by Julitium** [MiSTer-devel/C64_MiSTer#97]
Hi. 

The Core C64 for MiSTer has a bug in tape loading (many loaders) already fixed in MiST.

https://github.com/mist-devel/mist-binaries/issues/99

It is also very useful tape stop default (option?) and to have a key mapped to "Tape Play / Stop" (Prev. Page key for MiST) for multi-load games. 

Greetings.

P. E. : Lethal Weapon, OutRun Europe, etc

**Comment by lencio** [comment]
I tested on vice, and real c64 (on tapuino) the game "Lethal Weapon" and not work in mister c64 core.
I would be very grateful if that error could be fixed,
Link to tap file: https://www.planetemu.net/rom/commodore-c64-games-tap/lethal-weapon-1992-ocean-software

**Comment by sorgelig** [comment]
I've tried to load the tape and pause by default. As result you need to go to OSD additionally to start to playback.
I think you originally do it wrong. First - enter LOAD command, then open OSD and load the tape. And loading will start automatically. So it's already streamlined.

**Comment by lencio** [comment]
> I've tried to load the tape and pause by default. As result you need to go to OSD additionally to start to playback.
> I think you originally do it wrong. First - enter LOAD command, then open OSD and load the tape. And loading will start automatically. So it's already streamlined.

I’ll try this night. Thanks Alexey!!

**Comment by sorgelig** [comment]
Lethal Weapon and Co should load fine in new release

**Comment by lencio** [comment]
> Lethal Weapon and Co should load fine in new release

Thank a lot.
Great work!!

**Comment by Julitium** [comment]
Hi.
When you say pause I mean to understand that you mean Stop.
Yes, with the stop by default it is necessary to go to the OSD, that is why I suggested mapping that OSD option to a key not used by the implementation (in MiST it is Rev. Page key) that way it is equal to the real feeling of the machine .
Has someone ever loaded a tape without pressing Play? XD
I would be very grateful if it could be put like this.

I also want to inform you about the bug of some tape loaders. In MiST the thing came from the motor timing. I don't know if this is useful to you.

All the best.

**Comment by sorgelig** [comment]
> I also want to inform you about the bug of some tape loaders. In MiST the thing came from the motor timing. I don't know if this is useful to you.

are you talking about bug in today's release? which games don't load?

**Comment by sorgelig** [comment]
As for tape in general. It's good to load some tape game sometimes for fun, but other 99% of usage are disk games.

**Comment by Julitium** [comment]
No, now the upload works great.
I wrote the message without knowing that you had released a version.
The only thing I ask you is to have this option that I request "Default Tape State".
If we have less important options like "Pause on OSD", "Tape Sound", etc. I don't think it's unreasonable to include something like that.

Thank you very much for the new core.

All the best

**Comment by Julitium** [comment]
> As for tape in general: It's good to load some tape game sometimes for fun, but other 99% of usage are disk games.

Sorry, it's not my case and I think I'm not the only one.
In my case it is the reverse 1% Disk 99% Tape. So all the details are important to maximize recreation.

**Comment by rataweb** [comment]
Hi,
When you put LOAD, it jumps automatically SEARCHING message (pending you select TAP file from OSD), but Could you change this? I mean, It would be nice that it would show the message PRESS PLAY ON TAPE and then after selecting TAP file, continues with SEARCHING message and the load process.

Thanks and best regards,
Shark

**Comment by Julitium** [comment]
Hi. 

It's just that.
The C64 displays that message until the Play key is pressed.
I think the proposed feature is knocking on the right door.
With a Tape Default State option and a Play / Stop key it would meet any requirement with the use of Tapes.

Thanks.

All the best.

**Comment by sorgelig** [comment]
Core goes to search mode because of RTC. If you want it to wait, then disable RTC.

**Comment by Julitium** [comment]
Hi, 
I don't see the RTC - Tape relationship. You are the one who knows, I try. However, it would be necessary to map the OSD Play / Stop option to a key in some way.
Is this possible?
Thank you.
All the best

**Comment by sorgelig** [comment]
RTC is connected to tape port.

**Comment by Julitium** [comment]
Hi. 
I have already tried to remove RTC and indeed now the message appears but play is still magically pressed.

It can be fixed?

Thank you. 

All the best

**Comment by sorgelig** [comment]
RTC was for search activation even if no TAP is loaded.
New release has option to disable autoplay

**Comment by rataweb** [comment]
Thanks a lot for those changes!!! 
Congrats for your big job!!!

**Comment by Julitium** [comment]
Just perfect!!!

Thank you very much for your work and i apologize for any inconvenience caused.
Thanks again. 

All the best.
