### ISSUE TITLE
[Feature Request] Prophet64 .crt support

### ISSUE THREAD

**Issue by atrac17** [MiSTer-devel/C64_MiSTer#98]
Hello @sorgelig, would it be possible to add support for the Prophet64 software? It is a multi-cart. It doesn't run from the disk and cannot be successfully converted to any other cartridge format. 

Documentation for the cartridge format can be found [here](https://vice-emu.sourceforge.io/vice_17.html#SEC416). It works in [VICE](https://vice-emu.sourceforge.io/). Unfortunately you cannot rip it to a d64. It fails because the programs expect cartridge timing when loading sections of the cart bands (Program/UI).

If you require a .crt format of Prophet64, I can upload it to internet archive. Thank you for your consideration and improvements to the C64 core!

**Comment by sorgelig** [comment]
should be no problem to add. Is there a crt i can get for test?

**Comment by atrac17** [comment]
@sorgelig the link to the Prophet64.crt is [here](https://archive.org/details/prophet-64). Thank you again!

**Comment by atrac17** [comment]
Feature added. Thank you @sorgelig!  😃
